
include(ExternalProject)

set(OPENSSL_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/openssl-install-prefix")

unset(OPENSSL_OS_COMPILER)
unset(OPENSSL_CONFIG_EXTRA_ARGS)
unset(OPENSSL_BUILD_ENV)

if(ANDROID_ABI)
	if(ANDROID_ABI STREQUAL "armeabi-v7a")
		set(OPENSSL_OS_COMPILER "android-arm")
	elseif(ANDROID_ABI STREQUAL "arm64-v8a")
		set(OPENSSL_OS_COMPILER "android-arm64")
	elseif(ANDROID_ABI STREQUAL "x86")
		set(OPENSSL_OS_COMPILER "android-x86")
	elseif(ANDROID_ABI STREQUAL "x86_64")
		set(OPENSSL_OS_COMPILER "android-x86_64")
	endif()

	set(OPENSSL_CONFIG_EXTRA_ARGS "-D__ANDROID_API__=${ANDROID_NATIVE_API_LEVEL}")
else()
	if(UNIX AND NOT APPLE AND CMAKE_SIZEOF_VOID_P STREQUAL "8")
		set(OPENSSL_OS_COMPILER "linux-x86_64")
	endif()
endif()

if(NOT OPENSSL_OS_COMPILER)
	message(FATAL_ERROR "Failed to match OPENSSL_OS_COMPILER")
endif()

if(CMAKE_HOST_WIN32 AND ANDROID_ABI)
	##################
	# Windows 主机交叉编译（Android）：
	# OpenSSL 的 Configure/make 无法直接在 cmd 下运行（perl 脚本无扩展名、
	# PATH 分隔符、NDK 编译器探测等），改为通过 Git for Windows 的 bash
	# 执行，依赖：Git for Windows（bash/perl/cygpath）+ GNU make（如
	# GnuWin32 make 3.81）位于 PATH 中。
	##################

	find_program(OPENSSL_WIN_BASH
			NAMES bash.exe
			PATHS "$ENV{ProgramFiles}/Git/bin" "$ENV{ProgramFiles}/Git/usr/bin"
			"C:/Program Files/Git/bin" "C:/Program Files/Git/usr/bin"
			"C:/Program Files (x86)/Git/bin" "C:/Program Files (x86)/Git/usr/bin"
			NO_DEFAULT_PATH)
	if(NOT OPENSSL_WIN_BASH)
		# 兜底：任意 PATH 中的 bash（自定义 Git 安装位置等）
		find_program(OPENSSL_WIN_BASH NAMES bash.exe)
	endif()
	if(NOT OPENSSL_WIN_BASH)
		message(FATAL_ERROR "OpenSSL (Windows host): bash.exe not found. Install Git for Windows (or override with -DOPENSSL_WIN_BASH=<path-to-bash.exe>).")
	endif()

	find_program(OPENSSL_WIN_MAKE NAMES make)
	if(NOT OPENSSL_WIN_MAKE)
		message(FATAL_ERROR "OpenSSL (Windows host): make not found in PATH. Install GNU make for Windows (e.g. GnuWin32 make) and add it to PATH (or override with -DOPENSSL_WIN_MAKE=<path-to-make.exe>).")
	endif()

	# Git for Windows 自带的 perl 裁剪掉了 Pod::* 核心模块，而 OpenSSL 生成的
	# configdata.pm 在编译期会 `use Pod::Usage`（且构建期被 `-Mconfigdata` 反复
	# 加载）。放入源码树 Pod/ 目录即可被 @INC 中的 "." 命中；真正的
	# pod2usage() 仅在独立运行 configdata.pm / 构建文档时才会调用，不会发生。
	file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/openssl-win-pod-stub/Pod/Usage.pm"
"package Pod::Usage;
# Minimal stub: Git for Windows' bundled perl strips Pod::* core modules.
# OpenSSL's generated configdata.pm does \`use Pod::Usage\` at compile time inside
# an \`unless (caller)\` block, but pod2usage() is only invoked when configdata.pm
# runs standalone (e.g. \`perl configdata.pm --help\`), which never happens during
# Configure/build. util/process_docs.pl also calls it, but docs are not built.
use strict;
use warnings;
our \$VERSION = '1.36';

sub import { }

sub pod2usage {
    my (\$msg) = @_;
    die \"Pod::Usage stub: pod2usage called: \" . (defined \$msg ? \$msg : '') . \"\\n\";
}

1;
")

	# 构建步骤脚本（configure/build/install），由 ExternalProject 以
	# <SOURCE_DIR>/<INSTALL_DIR> 参数调用。ANDROID_NDK/API/目标 ABI 在
	# CMake configure 时嵌入（本脚本按 ABI 分目录生成）。
	file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/openssl-win-build-step.sh"
"#!/bin/bash
# Auto-generated by CMake (OpenSSLExternalProject.cmake) - Windows host build.
set -e
step=\"$1\"
src=\"$(cygpath -u \"$2\")\"
inst=\"$(cygpath -u \"$3\")\"
ndk=\"$(cygpath -u \"${ANDROID_NDK}\")\"
make_exe=\"$(cygpath -u \"${OPENSSL_WIN_MAKE}\")\"
api=\"${ANDROID_NATIVE_API_LEVEL}\"
target=\"${OPENSSL_OS_COMPILER}\"

# bash 由 ninja 直接启动，PATH 中通常没有 Git 的 /usr/bin（perl/rm/cp 等），
# 从 bash 自身路径推导并前置。
git_usr_bin=\"$(dirname \"$BASH\")\"

export ANDROID_NDK_HOME=\"$ndk\"
export PATH=\"$git_usr_bin:$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin:$PATH\"

cd \"$src\"
case \"$step\" in
	configure)
		# 清理上次失败运行可能残留的半成品：空的时间戳较新的生成文件会
		# 让 make 跳过重新生成，导致后续编译出现大量未定义宏错误。
		rm -f configdata.pm Makefile
		rm -f include/openssl/opensslconf.h include/crypto/bn_conf.h include/crypto/dso_conf.h
		perl Configure --prefix=\"$inst\" no-shared -D__ANDROID_API__=\"$api\" \"$target\"
		;;
	build)
		\"$make_exe\" -j4 build_generated
		\"$make_exe\" -j4 build_libs
		;;
	install)
		\"$make_exe\" install_dev
		;;
esac
")

	ExternalProject_Add(OpenSSL-ExternalProject
			URL file://${CMAKE_CURRENT_SOURCE_DIR}/third-party/openssl-1.1.1s.tar.gz
			# URL https://www.openssl.org/source/openssl-1.1.1d.tar.gz
			# URL_HASH SHA256=c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa
			INSTALL_DIR "${OPENSSL_INSTALL_DIR}"
			PATCH_COMMAND ${CMAKE_COMMAND} -E copy_directory
				"${CMAKE_CURRENT_BINARY_DIR}/openssl-win-pod-stub/Pod" "<SOURCE_DIR>/Pod"
			CONFIGURE_COMMAND "${OPENSSL_WIN_BASH}" "${CMAKE_CURRENT_BINARY_DIR}/openssl-win-build-step.sh" configure "<SOURCE_DIR>" "<INSTALL_DIR>"
			BUILD_COMMAND "${OPENSSL_WIN_BASH}" "${CMAKE_CURRENT_BINARY_DIR}/openssl-win-build-step.sh" build "<SOURCE_DIR>" "<INSTALL_DIR>"
			INSTALL_COMMAND "${OPENSSL_WIN_BASH}" "${CMAKE_CURRENT_BINARY_DIR}/openssl-win-build-step.sh" install "<SOURCE_DIR>" "<INSTALL_DIR>")
else()
	# Android 交叉编译（Linux/macOS 主机）：与原实现一致，把 NDK 工具链前置到 PATH
	if(ANDROID_ABI)
		get_filename_component(ANDROID_NDK_BIN_PATH "${CMAKE_C_COMPILER}" DIRECTORY)
		set(OPENSSL_BUILD_ENV "ANDROID_NDK_HOME=${ANDROID_NDK}" "PATH=${ANDROID_NDK_BIN_PATH}:$ENV{PATH}")
	endif()

	find_program(MAKE_EXE NAMES gmake make)
	ExternalProject_Add(OpenSSL-ExternalProject
			URL file://${CMAKE_CURRENT_SOURCE_DIR}/third-party/openssl-1.1.1s.tar.gz
			# URL https://www.openssl.org/source/openssl-1.1.1d.tar.gz
			# URL_HASH SHA256=c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa
			INSTALL_DIR "${OPENSSL_INSTALL_DIR}"
			CONFIGURE_COMMAND ${CMAKE_COMMAND} -E env ${OPENSSL_BUILD_ENV}
				"<SOURCE_DIR>/Configure" "--prefix=<INSTALL_DIR>" no-shared ${OPENSSL_CONFIG_EXTRA_ARGS} "${OPENSSL_OS_COMPILER}"
			BUILD_COMMAND ${CMAKE_COMMAND} -E env ${OPENSSL_BUILD_ENV} "${MAKE_EXE}" -j4 build_libs
			INSTALL_COMMAND ${CMAKE_COMMAND} -E env ${OPENSSL_BUILD_ENV} "${MAKE_EXE}" install_dev)
endif()

add_library(OpenSSL_Crypto INTERFACE)
add_dependencies(OpenSSL_Crypto OpenSSL-ExternalProject)
if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.13.0")
	target_link_directories(OpenSSL_Crypto INTERFACE "${OPENSSL_INSTALL_DIR}/lib")
else()
	link_directories("${OPENSSL_INSTALL_DIR}/lib")
endif()
target_link_libraries(OpenSSL_Crypto INTERFACE crypto)
target_include_directories(OpenSSL_Crypto INTERFACE "${OPENSSL_INSTALL_DIR}/include")
